
# Пишет в консоль ошибку
def error(message_error: str):
    print('Error:', message_error)
